export const sizes = {
  SMALL_LOGO_SIZE: '44px',
  NAV_IMGS_SIZE: '28px',
  CLOSE_BTN_SIZE: '24px',
  EMPTY_IMG_SIZE: '80px',
  EMPTY_DND_SIZE: '48px',
  TRIP_SUMMARY_SIZE: '64px',
  TRASH_ICON_SIZE: '24px',
  CALENDAR_ICON_SIZE: '24px',
  ARROW_ICON_SIZE: '24px',
};
